name: 🐛 Bug Report
description: Report a bug or issue
labels: ["bug", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting this bug! Please provide detailed information to help us fix it.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is
      placeholder: |
        What happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should happen instead?
      placeholder: The feature should work correctly
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        - OS: (Windows/Mac/Linux)
        - Browser: (Chrome/Firefox/Safari)
        - Node version: (if applicable)
      placeholder: |
        OS: Windows 11
        Browser: Chrome 120
        Node: 18.x
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or error logs
      description: Add any relevant screenshots or error messages
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched for existing issues
          required: true
        - label: I can reproduce the issue
          required: true
        - label: I have included screenshots or logs
          required: false
