name: ✨ Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement", "feature-request"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Your ideas help improve PsychoAnalyze AI.

  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: Clear description of the feature you want
      placeholder: |
        What feature would you like to see?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why do you need this feature?
      placeholder: |
        What problem does this solve?
        What's your use case?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative solutions
      description: Any alternative approaches you've considered?
      placeholder: |
        What other approaches could work?
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Examples of similar features or implementations
      placeholder: |
        Are there similar features in other tools?
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched for existing feature requests
          required: true
        - label: This feature would be useful to others
          required: false
